spring.application.name=order
server.port=8080
server.servlet.context-path=/api

# --- datasource (order-db) ---
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:orderdb}
spring.datasource.username=${POSTGRES_DB_USER:orderuser}
spring.datasource.password=${POSTGRES_DB_PASSWORD:secret}
spring.jpa.open-in-view=false

# --- kafka ---
spring.kafka.bootstrap-servers=${KAFKA_SERVERS:localhost:29092}
#cosmetic field, named after associated service for easy readability in logs
spring.kafka.client-id=order-service
#group.id decides which partitions the service will be assigned and how offset-commit identity is stored so the service can remember where it left off
spring.kafka.consumer.group-id=order-service
#enable-auto-commit advances the offset with a simple timer regardless of success, defeating the purpose of DefaultErrorHandler's retries and our DLT
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest
#assigning concurrency=2 is actually dead weight, it means each listener gets two threads, but the two listeners in order-service each listen to one topic with one partition, which you only need one thread for 
spring.kafka.listener.concurrency=2
# false: the participant outbox topics may not exist yet at orchestrator startup
spring.kafka.listener.missing-topics-fatal=false

# --- saga response topics the orchestrator listens on (participant outbox -> order inbox) ---
# Inside order-service these topics are considered inboxes because messages come in from payment-service and inventory-service but the larger system (all application.properties, *-outbox-connector.json files, participant services) considers them the outboxes of participant services
kafka.topic.saga.payment.inbox.events=payment.outbox.events
kafka.topic.saga.inventory.inbox.events=inventory.outbox.events
